### ISSUE TITLE
Please, how to upgrade RetroArch in CrossMix OS and use the AI Service?

### ISSUE THREAD

**Issue by giancarlozero** [cizia64/CrossMix-OS#272]
I wish to upgrade RetroArch in my Trimui Smart Pro with Crossmix OS to the version 1.19.1, to use the AI Service/text translation service. But I don't know how to do this.

The RetroArch version installed now is 1.18.0.

Can you help me?

(Sorry about my poor english. It's not my native language)

**Comment by cizia64** [comment]
Hi you can't update RetroArch because CrossMix use a version provided by TrimUI which provide some additional features like the in game menu which allows to save and load save states.
On the Brick Retroarch has been updated to version 1.19.1 so may be one day I will use it in CrossMix however it doesn't include AI features neither :/

**Comment by giancarlozero** [comment]
All right then. I hope this will be possible in the future.

Thank you very much and keep up the great work! CrossMix OS is amazing!
