### ISSUE TITLE
Allow scraping boxart+screenshots and displaying them

### ISSUE THREAD

**Issue by raschagas** [cizia64/CrossMix-OS#34]
I've noticed only boxarts are downloaded with Scraper. And I can't find out how to display boxart+screenshots, like the stock OS does.

**Comment by cizia64** [comment]
Hi, may be the next update of the Scraper will fit with your expectations ?
Take a look to "ScreenScraper Mix V1" & "ScreenScraper Mix V2" [here](https://github.com/schmurtzm/TrimUI-Smart-Pro/tree/main/Scraper#medias-description), otherwise to make your own it's not easy because you have to download each asset and mix them directly on the device.
The new scraper will be updated probably for CrossMix v1.1.1
